default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("POSTGRES_HOST") { 'localhost' } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { '5432' } %>
  database: <%= ENV.fetch("POSTGRES_DB") { 'postgres' } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { 'postgres' } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { 'postgres' } %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
